project_name: "Projector"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Human Review", "Done"]
labels: []
definition_of_done: []
date_format: yyyy-mm-dd
max_column_width: 20
default_editor: "nvim"
auto_open_browser: true
default_port: 9471
remote_operations: true
auto_commit: false
bypass_git_hooks: false
check_active_branches: true
active_branch_days: 10
task_prefix: "PROJ"
